fix: add raise:false
error: Before process_action callback :verify_authenticity_tokens has not been defined
 if skip_before_action is called multiple times with the same method name, this exception will be raised.